// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsSjbrmAl0ElKKUqFJSqIN-5Q0fPFlR84',
    appId: '1:163090057373:web:9c4c5ad419f9ad9c66ec74',
    messagingSenderId: '163090057373',
    projectId: 'wan-monitor',
    authDomain: 'wan-monitor.firebaseapp.com',
    storageBucket: 'wan-monitor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYPk0n-bVWZhVa1fqbq1BWPjVFe8E7ow',
    appId: '1:163090057373:android:4e6575952b9b582866ec74',
    messagingSenderId: '163090057373',
    projectId: 'wan-monitor',
    storageBucket: 'wan-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrT8wiUf-9nmhz5hhNwTI5SRvOXM7kgU8',
    appId: '1:163090057373:ios:850d4f2b08c9a4af66ec74',
    messagingSenderId: '163090057373',
    projectId: 'wan-monitor',
    storageBucket: 'wan-monitor.firebasestorage.app',
    iosBundleId: 'com.aris.wanmonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrT8wiUf-9nmhz5hhNwTI5SRvOXM7kgU8',
    appId: '1:163090057373:ios:cf1f7d781ee9b59666ec74',
    messagingSenderId: '163090057373',
    projectId: 'wan-monitor',
    storageBucket: 'wan-monitor.firebasestorage.app',
    iosBundleId: 'com.example.wanMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsSjbrmAl0ElKKUqFJSqIN-5Q0fPFlR84',
    appId: '1:163090057373:web:9092d9315794dbe766ec74',
    messagingSenderId: '163090057373',
    projectId: 'wan-monitor',
    authDomain: 'wan-monitor.firebaseapp.com',
    storageBucket: 'wan-monitor.firebasestorage.app',
  );
}
